Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/01/2022
Var
// Seção de Declarações das variáveis 
    n:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

    para n de 1 ate 10 faca
    escreva(n)
         fimpara


Fimalgoritmo
